In [2]:
import numpy as np
import pandas as pd

In [3]:
t = (1,2,3)
a = np.array(t,dtype = 'int32')#把一个list或者tuple转化为一个array
a

array([1, 2, 3])

In [4]:
t1 = [1,2,3]
b = np.array(t,dtype = 'int32')#把一个list或者tuple转化为一个array
b

array([1, 2, 3])

In [6]:
c = np.array([[1,2],[3,4]],dtype = 'complex')
c #通过临时list直接生成

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

np中产生固定数组的方法

In [9]:
d = np.ones([2,3])
d1 = np.zeros([3,4])
print(d)
print(d1)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [14]:
e = np.eye(3,3)#产生一个对角矩阵
e

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [16]:
e1 = np.eye(3,4)
e1

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [17]:
np.arange(2,10,2)#左闭右开区间

array([2, 4, 6, 8])

In [20]:
np.linspace(0,10,4)#生成一个线性的数组(0,10)的4个数组

array([  0.        ,   3.33333333,   6.66666667,  10.        ])