In [1]:
import numpy as np

In [2]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [3]:
a[2] #可以看到和matlab不同，python中是从0开始的标号.
#翻译代码的时候需要特别注意

4

In [4]:
a[2:4] #可使用:运算符来索引，这个与matlab中是同样的

array([4, 9], dtype=int32)

In [5]:
a_slice = a[2:4]
a_slice[0]=5
a
#特别注意！！！ 使用slice并不是复制出的副本，而是对于原数组a的地址的储存
#当对a_slice操作的时候原数组a也受到了明细的影响！

array([ 0,  1,  5,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [6]:
#如果使用slice复制出一个相互独立的数组的话也可以
a_slicecopy = a[2:4].copy()
print(a_slicecopy)
a_slicecopy[0] = 4
print(a_slicecopy)
print(a)

[5 9]
[4 9]
[ 0  1  5  9 16 25 36 49 64 81]


多维数组

In [7]:
def f(y,x):
    return 4 * x + y
b = np.fromfunction(f,(3,2),dtype = int) 
#这个函数相当于把每个值的所在的维数作为
#函数的输入,注意也是从0开始计数的！
#而且严格按照函数定义的变量的顺序进行
print(b)

[[0 4]
 [1 5]
 [2 6]]


In [8]:
b[0]

array([0, 4])

In [9]:
print(b[0][1]) #选中元素的方法
print(b[0,1])
print(b[:,1])

4
4
[4 5 6]


In [10]:
c = np.zeros([4,5])
print(c)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [11]:
column_length = c.shape[1]
column_length

5

In [12]:
for i in range(c.shape[0]):
    c[i]=i 
    print(c[i])
c

[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.]
[ 3.  3.  3.  3.  3.]


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.]])

Boolean Indexing

In [13]:
week_days = np.array(['Monday','Tuesday','Wednesday','Thursday','Friday'])

In [14]:
work_time = np.round(np.random.randn(5,5) + 8.0 , 2)
print(work_time.T)
work_time

[[ 6.87  7.53  7.33  6.94  7.3 ]
 [ 7.16  7.67  7.06  8.22  7.91]
 [ 9.58  7.74  9.61  9.39  7.64]
 [ 9.12  7.01  8.25  7.8   7.97]
 [ 9.38  9.12  8.    8.35  7.29]]


array([[ 6.87,  7.16,  9.58,  9.12,  9.38],
       [ 7.53,  7.67,  7.74,  7.01,  9.12],
       [ 7.33,  7.06,  9.61,  8.25,  8.  ],
       [ 6.94,  8.22,  9.39,  7.8 ,  8.35],
       [ 7.3 ,  7.91,  7.64,  7.97,  7.29]])

In [15]:
week_days == 'Monday'

array([ True, False, False, False, False], dtype=bool)

In [21]:
work_time[week_days == 'Monday',2] #返回的是某一行，继续加入第二个坐标
#我们就得到第i个坐标处的数组，从0开始计数。

array([ 9.58])