In [9]:
import numpy as np
import pandas as pd

In [10]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a)
a.shape

[[[1 2 3]
  [4 5 6]]]


(1, 2, 3)

In [11]:
print(a.T) #矩阵转置
a.T.shape

[[[1]
  [4]]

 [[2]
  [5]]

 [[3]
  [6]]]


(3, 2, 1)

In [12]:
a2 = a.transpose(0,2,1)
print(a2) #矩阵转置函数选择交换的维度
#以上的含义就是0与0维换
#1与2维换
#2与1维换
a2.shape

[[[1 4]
  [2 5]
  [3 6]]]


(1, 3, 2)

In [13]:
a = np.array([[1,2,3],[5,5,6]]);
print(a)
print(a.T)
print(np.dot(a.T,a))

[[1 2 3]
 [5 5 6]]
[[1 5]
 [2 5]
 [3 6]]
[[26 27 33]
 [27 29 36]
 [33 36 45]]


In [14]:
#求逆矩阵
inv_a = np.array([[1,2],[5,8]])
inverse1 = np.linalg.inv(inv_a)

In [15]:
test_Matrix = np.dot(inv_a,inverse1)

In [16]:
np.allclose(test_Matrix,np.eye(inv_a.shape[0])) #判断两个矩阵是不是相等

True

三维矩阵

In [20]:
a_3d = np.arange(50).reshape([5,5,2])
a_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [23]:
a_3d.transpose([0,2,1])
#原来矩阵a_3d的维度，按照原来的第0,2,1维上的规模转置
#比如原来11的位置是(1,0,1)变换之后变到(1,1,0)的位置

array([[[ 0,  2,  4,  6,  8],
        [ 1,  3,  5,  7,  9]],

       [[10, 12, 14, 16, 18],
        [11, 13, 15, 17, 19]],

       [[20, 22, 24, 26, 28],
        [21, 23, 25, 27, 29]],

       [[30, 32, 34, 36, 38],
        [31, 33, 35, 37, 39]],

       [[40, 42, 44, 46, 48],
        [41, 43, 45, 47, 49]]])

In [25]:
a_3d.transpose([1,2,0])

array([[[ 0, 10, 20, 30, 40],
        [ 1, 11, 21, 31, 41]],

       [[ 2, 12, 22, 32, 42],
        [ 3, 13, 23, 33, 43]],

       [[ 4, 14, 24, 34, 44],
        [ 5, 15, 25, 35, 45]],

       [[ 6, 16, 26, 36, 46],
        [ 7, 17, 27, 37, 47]],

       [[ 8, 18, 28, 38, 48],
        [ 9, 19, 29, 39, 49]]])

In [36]:
a_2d = np.array([[1,2],[3,4]])
print(a_2d)
a_2d.swapaxes(1,0)

[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

In [45]:
a_bincun = np.array([1,3,3,5,1,2,7,4])
np.bincount(a_bincun)
#这个bincount是统计在一个一维array中的0-max的个数

array([0, 2, 1, 2, 1, 1, 0, 1], dtype=int64)