In [1]:
import numpy as np

In [2]:
#以np.add函数为例
#reduce方法可以降维，将某一个维度上的值求和
a = np.array([1,2,3,4])
np.add.reduce(a)

10

In [3]:
#多维数组默认只按照第一维进行运算：
a = np.array([[1,2,3],[4,5,6]])

np.add.reduce(a)

array([5, 7, 9])

In [6]:
#指定维度
np.add.reduce(a, axis = 1)

array([ 6, 15])

In [8]:
#作用于字符串：
a = np.array(['ab', 'cd', 'ef'],np.object)

np.add.reduce(a)

'abcdef'

In [10]:
#逻辑运算
a = np.array([1,1,0,1])

np.logical_and.reduce(a)

False

In [11]:
np.logical_or.reduce(a)

True

In [12]:
#accumulate 方法,类似于matlab的cumsum
a = np.array([1,2,3,4])

np.add.accumulate(a)

array([ 1,  3,  6, 10], dtype=int32)

In [15]:
#如果是多维数组，也是降维的思路
a = np.array([[1,2,3],[4,5,6]])

np.add.accumulate(a,axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [16]:
a = np.array(['ab', 'cd', 'ef'], np.object)

np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

In [17]:
a = np.array([1,1,0,1])

np.logical_and.accumulate(a)

array([ True,  True, False, False], dtype=bool)

In [18]:
np.logical_or.accumulate(a)

array([ True,  True,  True,  True], dtype=bool)

In [19]:
#reduceat 方法
a = np.array([0, 10, 20, 30, 40, 50])
indices = np.array([1,4])

np.add.reduceat(a, indices)
#这里，indices 为 [1, 4]，所以 60 表示从下标1（包括）
#加到下标4（不包括）的结果，
#90 表示从下标4（包括）加到结尾的结果。

array([60, 90], dtype=int32)

In [20]:
#outer 方法
a = np.array([0,1])
b = np.array([1,2,3])

np.add.outer(a, b)
#对于 a 中每个元素，将 op 运用到它和 b 
#的每一个元素上所得到的结果：

array([[1, 2, 3],
       [2, 3, 4]])

In [21]:
#the sequence will work

In [22]:
np.add.outer(b, a)

array([[1, 2],
       [2, 3],
       [3, 4]])