In [1]:
import numpy as np

In [2]:
a = np.array([1,2])

In [3]:
a*3

array([3, 6])

In [4]:
#数组逐元素相乘:
a = np.array([1,2])
b = np.array([3,4])
a * b

array([3, 8])

In [5]:
#等于操作也是逐元素比较的：
a = np.array([[1,2,3,4],
              [2,3,4,5]])
b = np.array([[1,2,3,4],
              [1,3,4,5]])
a == b

array([[ True,  True, False,  True],
       [False,  True,  True,  True]], dtype=bool)

In [10]:
#如果要判断两个数组是否相等，应该使用np.all
if np.all(a==b):
    print("yes")
else:
    print("no")

no


In [12]:
#对于浮点数，由于存在精度问题，使用函数 allclose 会更好：
if np.allclose(a,b):
    print("yes")
else:
    print("no")

no


In [13]:
#logical_and逐元素的and操作
#0 被认为是 False，非零则是 True。
a = np.array([0,1,2])
b = np.array([0,10,0])

np.logical_and(a, b)

array([False,  True, False], dtype=bool)

In [18]:
a = np.array([1,2,4,255])
b = np.array([16,32,64,129])

a | b
#a是uint8

<class 'numpy.int32'>


array([ 17,  34,  68, 255], dtype=int32)

In [19]:
#取反：
a = np.array([1,2,3,4], np.uint8)
~a

array([254, 253, 252, 251], dtype=uint8)

In [20]:
#左移：
a << 3

array([ 8, 16, 24, 32], dtype=uint8)

In [21]:
#要注意的是 & 的运算优先于比较运算如 > 等，
#所以必要时候需要加上括号：
a = np.array([1,2,4,8])
b = np.array([16,32,64,128])

(a > 3) & (b < 100)

array([False, False,  True, False], dtype=bool)