In [1]:
import numpy as np

In [2]:
a = np.array([11,21,31,12,22,32,13,23,33])
a.shape = 3,3
a

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [3]:
#查看对角线元素
a.diagonal()

array([11, 22, 33])

In [4]:
#可以使用偏移来查看它的次对角线，正数表示右移，负数表示左移：
a.diagonal(offset=1)

array([21, 32])

In [5]:
a.diagonal(offset=-1)

array([12, 23])

In [6]:
#使用花式索引获取对角线
i = [0,1,2]
a[i, i]

array([11, 22, 33])

In [7]:
a[i,i] =2

In [8]:
a

array([[ 2, 21, 31],
       [12,  2, 32],
       [13, 23,  2]])

In [9]:
b = np.arange(6)
b.shape = 2,3

In [10]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
#即使不是方阵，也是可以具有diagonal的
b.diagonal()

array([0, 4])