In [1]:
import numpy as np

In [2]:
names = np.array(['bob', 'sue', 'jan', 'ad'])
weights = np.array([20.8, 93.2, 53.4, 61.8])


In [3]:
#sort函数对数组进行排序,默认升序排列
np.sort(weights)

array([ 20.8,  53.4,  61.8,  93.2])

In [11]:
#argsort函数返回从小到达的排列在数组中的索引位置
ordered_indices = np.argsort(weights)
#ordered_indices = np.argsort(ordered_indices)
ordered_indices


array([0, 2, 3, 1], dtype=int64)

In [12]:
#可以使用ordered_indices索引
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'],
      dtype='<U3')

In [10]:
#如果我想知道，数组中某元素在升序排列中的位置可以按下面的方法
ordered_indices = np.argsort(weights)
ordered_indices = np.argsort(ordered_indices)
ordered_indices

array([0, 3, 1, 2], dtype=int64)

In [14]:
#data.sort()会改变数组的数值
data = np.array([20.8,  93.2,  53.4,  61.8])
data.sort()
data

array([ 20.8,  53.4,  61.8,  93.2])

In [17]:
#searchsorted(sorted_array, values)

#searchsorted 接受两个参数，其中，第一个必需是已排序的数组。

sorted_array = np.linspace(0,1,5)
values = np.array([-0.1,.8,.3,.12,.5,.25])
np.searchsorted(sorted_array, values)

array([0, 4, 2, 1, 2, 1], dtype=int64)

In [19]:
#利用插入位置，将数组中所有在这两个值之间的值提取出来：

data = np.random.rand(100)
data.sort()

bounds = (.4, .6)

low_idx, high_idx = np.searchsorted(data, bounds)

data[low_idx:high_idx]

array([ 0.40095603,  0.40840833,  0.42724989,  0.42881575,  0.42987878,
        0.43647841,  0.44510282,  0.44651268,  0.46122915,  0.46555381,
        0.47641075,  0.47824711,  0.47855132,  0.48073022,  0.48141074,
        0.48235804,  0.52128873,  0.52898579,  0.53608751,  0.54615689,
        0.54936746,  0.55355937,  0.56191844,  0.56269774,  0.57612021,
        0.599667  ])

In [27]:
#利用插入位置，将数组中所有在这两个值之间的值提取出来：

data[(data>0.4)&(data<0.6)]

array([ 0.40095603,  0.40840833,  0.42724989,  0.42881575,  0.42987878,
        0.43647841,  0.44510282,  0.44651268,  0.46122915,  0.46555381,
        0.47641075,  0.47824711,  0.47855132,  0.48073022,  0.48141074,
        0.48235804,  0.52128873,  0.52898579,  0.53608751,  0.54615689,
        0.54936746,  0.55355937,  0.56191844,  0.56269774,  0.57612021,
        0.599667  ])