In [5]:
import numpy as np

In [6]:
a = np.array([[1,2,3], 
             [4,5,6]])

In [7]:
#求所有元素的和

In [8]:
sum(a)

array([5, 7, 9])

In [9]:
#可以指定求和的维度
np.sum(a,axis = 0)#列

array([5, 7, 9])

In [10]:
#沿着第二维求和
np.sum(a,axis = 1)#行

array([ 6, 15])

In [11]:
#求所有元素的成绩,同样可以指定维度
np.prod(a,axis = 0)#

array([ 4, 10, 18])

In [12]:
from numpy.random import rand

In [13]:
a = rand(3,4)
%precision 5
a

array([[ 0.97581,  0.65165,  0.35351,  0.8357 ],
       [ 0.03896,  0.78382,  0.98296,  0.0103 ],
       [ 0.03756,  0.05023,  0.55424,  0.73382]])

In [14]:
a.min()#全局最小值

0.01030

In [15]:
a.min(axis = 0)

array([ 0.03756,  0.05023,  0.35351,  0.0103 ])

In [16]:
#全局最大
a.max()

0.98296

In [17]:
#某个维度最大
a.max(axis = 1)

array([ 0.97581,  0.98296,  0.73382])

In [18]:
#求最大最小值的位置的方法
a.argmin()

7

In [19]:
a.argmin(axis = 0)#每一列的最小值的位置

array([2, 2, 0, 1], dtype=int64)

In [21]:
a = np.array([[1,2,3],[4,5,6]])

In [22]:
a.mean()

3.50000

In [23]:
a.mean(axis = -1)

array([ 2.,  5.])

In [25]:

np.average(a, axis = 0)

array([ 2.5,  3.5,  4.5])

In [32]:
#average 函数还支持加权平均：
np.average(a, axis = 0, weights=[0.1,0.2],returned = True)

(array([ 3.,  4.,  5.]), array([ 0.3,  0.3,  0.3]))

In [34]:
#std方法计算标准差
print(np.std(a))
print(np.std(a,axis = 1))

1.70782512766
[ 0.8165  0.8165]


In [35]:
#用var方法计算方差
print(np.var(a))
print(np.var(a,axis = 1))

2.91666666667
[ 0.66667  0.66667]


In [36]:
#clip方法，将数值限制在某个范围
print(a)
a.clip(3,5)

[[1 2 3]
 [4 5 6]]


array([[3, 3, 3],
       [4, 5, 5]])

In [37]:
#计算极差ptp 方法
a.ptp(axis = 1)

array([2, 2])

In [39]:
a = np.array([1.35, 2.5, 1.5])

In [41]:
#round方法近似到n位小数
#如果不输入参数，默认为近似到整数，
#如果出现0.5，默认近似到最近的偶数值
a.round()

array([ 1.,  2.,  2.])

In [43]:
a.round(decimals = 1)

array([ 1.4,  2.5,  1.5])