In [1]:
import numpy as np

a = np.array([[1,2],
           [3,4]], 
          dtype = np.uint8)

In [2]:
a.tostring()

b'\x01\x02\x03\x04'

In [3]:
#此时，返回的数组是一维的，需要重新设定维度：
s = a.tostring()
a = np.fromstring(s, 
                  dtype=np.uint8)
a

array([1, 2, 3, 4], dtype=uint8)

In [4]:
a.shape = 2,2
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [13]:
np.loadtxt(r'F:\python\Jupyter\Numpy\float.txt')

array([[ 3.3,  2.2,  4.4,  5.5],
       [ 6.6,  7.7,  8.8,  9.9]])

In [42]:
np.savetxt(r'F:\python\Jupyter\Numpy\float1.txt',fmt ='%.3f',X=a,delimiter = '\n',newline = '\n')

In [24]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)