In [1]:
import numpy as np

In [2]:
a =np.arange(0,6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [7]:
#使用reshape生成一个形状变换的数组
#生成一个三行两列的数组s
np.reshape(a,[3,2])

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a = np.arange(3)
np.shape(a)

(3,)

In [13]:
y = a[np.newaxis, :]

In [14]:
y

array([[0, 1, 2]])

In [15]:
#从一维数组变成了二维数组
np.shape(y)

(1, 3)

In [16]:
#根据不同的位置可以产生不同维度的
y = a[:, np.newaxis]
y

array([[0],
       [1],
       [2]])

In [17]:
y = a[np.newaxis,np.newaxis, :]
y

array([[[0, 1, 2]]])

In [18]:
np.shape(y)

(1, 1, 3)

In [21]:
a = np.arange(6)
a
#a.shape(2,1,3)

array([0, 1, 2, 3, 4, 5])

In [23]:
a.shape = 2,1,3
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [24]:
#squeeze方法去除多余的轴
b = a.squeeze()

In [25]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [26]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [27]:
#返回数组的转置
#3,1,2 : 3个1行两列
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [ ]:
#注意:
#对于复数数组，转置并不返回复共轭，只是单纯的交换轴的位置
#转置可以作用于多维数组

In [28]:
a = np.arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [31]:
np.shape(a)

(3, 4, 5)

In [32]:
a[:,1,:]

array([[ 5,  6,  7,  8,  9],
       [25, 26, 27, 28, 29],
       [45, 46, 47, 48, 49]])

In [33]:
a[:,:,1]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [35]:
a[1,:,:]

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [37]:
a = np.arange(6)
a.shape = (2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
#修改转置原数组的值也改变：
b = a.T
b[0,1] = 30
print(a)

[[ 0  1  2]
 [30  4  5]]


In [39]:
#数组链接
#有时我们需要将不同的数组按照一定的顺序连接起来：

#concatenate((a0,a1,...,aN), axis=0)
#注意，这些数组要用 () 包括到一个元组中去。

#除了给定的轴外，这些数组其他轴的长度必须是一样的。
x = np.array([
        [0,1,2],
        [10,11,12]
    ])
y = np.array([
        [50,51,52],
        [60,61,62]
    ])
print (x.shape)
print (y.shape)

(2, 3)
(2, 3)


In [41]:
z = np.concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [43]:
z = np.concatenate((x,y), axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [45]:
#注意到这里 x 和 y 的形状是一样的，还可以将它们连接成三维的数组，
#但是 concatenate 不能提供这样的功能，不过可以这样：
z = np.array((x,y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

In [46]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

In [49]:
#flatten 方法的作用是将多维数组转化为1维数组：
b = a.flatten()
b

array([ 0,  1,  2, 30,  4,  5])

In [50]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

In [51]:
#flat 属性
a.flat

In [52]:
#a.flat 相当于返回了所有元组组成的一个迭代器：
b = a.flat

In [53]:
b[0]

0

In [54]:
b[2]

2

In [55]:
b[3]

30

In [57]:
#但此时修改 b 的值会影响 a ：
b[3] = 0

In [58]:
a

array([[0, 1, 2],
       [0, 4, 5]])

In [60]:
#如果想要直接查看flat()的值我们可以使用:运算符
a.flat[:]

array([0, 1, 2, 0, 4, 5])

In [61]:
#ravel方法也提供上述功能
a.ravel()

array([0, 1, 2, 0, 4, 5])

In [65]:
#可以看到，在这种情况下，修改 b 并不会改变 aa 的值
#原因是我们用来 ravel 的对象 aa 本身是 a 的一个view。
aa = a.transpose()
b = aa.ravel()
b[0] = 10
b


array([10,  0,  1,  4,  2,  5])

In [66]:
aa

array([[0, 0],
       [1, 4],
       [2, 5]])

In [67]:
a

array([[0, 1, 2],
       [0, 4, 5]])