In [1]:
import numpy as np

In [2]:
#mat()方法将array变成Matrix
import numpy as np
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [3]:
#也可以使用 Matlab 的语法传入一个字符串来生成矩阵：
A = np.mat('1,2,3;4,5,6;7,8,9')

In [4]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [5]:
#可以利用分块构建bmat()新的矩阵
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [6]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [7]:
#矩阵与向量的乘法
A * x

matrix([[14],
        [32],
        [50]])

In [10]:
x1 = np.mat('1;2;3')
x1

matrix([[1],
        [2],
        [3]])

In [9]:
#矩阵的乘法
A *x1

matrix([[14],
        [32],
        [50]])

In [24]:
#A.I表示A矩阵的逆矩阵

np.linalg.inv(A) *A

matrix([[ 12. ,  16. ,  12. ],
        [-10. , -16. ,  -6. ],
        [  1.5,   4. ,   2.5]])

In [17]:
#**表示矩阵的连乘
A*A*A*A

matrix([[ 7560,  9288, 11016],
        [17118, 21033, 24948],
        [26676, 32778, 38880]])

In [18]:
A**4

matrix([[ 7560,  9288, 11016],
        [17118, 21033, 24948],
        [26676, 32778, 38880]])

matrix([[  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15],
        [ -6.30503948e+15,   1.26100790e+16,  -6.30503948e+15],
        [  3.15251974e+15,  -6.30503948e+15,   3.15251974e+15]])

In [30]:
A = np.mat([[1,-2,1],[0,2,-1],[1,1,-2]])
A_ = np.linalg.inv(A)
A*A_

matrix([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  1.11022302e-16,   1.00000000e+00,  -1.11022302e-16],
        [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [31]:
#求矩阵的秩
A = np.mat('1,2,3;4,5,6;7,8,9')

In [39]:
print(A.ndim)
print(np.linalg.matrix_rank(A))
print(A.shape)
#所以上面的A不满秩不可逆
np.linalg.det(A)#这个值近似为0

2
2
(3, 3)


-9.5161973539299405e-16