In [1]:
#希望定义一个一维数组，
#每个元素有三个属性 name, age, wgt，
#此时我们需要使用结构化数组。

In [2]:
import numpy as np

In [3]:
a = np.array([1.0,2.0,3.0,4.0], np.float32)

In [5]:
a.view(np.complex64)
#将a按照复数的形式来解释内存
#对于复数而言就相当于具有实部和虚部两个属性的结构体

array([ 1.+2.j,  3.+4.j], dtype=complex64)

In [20]:
#定义自己需要的数据类型,我们可以使用my_dtype
my_dtype = np.dtype([('mass', 'float32'), ('vol', 'float32')])

In [21]:
my_data = np.array([(1,1), (1,2), (2,1), (1,3)],dtype =  my_dtype)

print (my_data)

[( 1.,  1.) ( 1.,  2.) ( 2.,  1.) ( 1.,  3.)]


In [22]:
my_data[1]#可以进行索引

( 1.,  2.)

In [23]:
my_data[1]['vol']#可以对自定义的元素进行属性索引

2.0

In [24]:
#得到所有的质量信息
my_data['mass']

array([ 1.,  1.,  2.,  1.], dtype=float32)

In [25]:
#自定义排序规则，先按速度，再按质量：
my_data.sort(order=('vol', 'mass'))

print (my_data)

[( 1.,  1.) ( 2.,  1.) ( 1.,  2.) ( 1.,  3.)]


In [26]:
#查看类型所占字节
person_dtype = np.dtype([('name', 'S10'), ('age', 'int'), ('weight', 'float')])

In [27]:
person_dtype.itemsize

22

In [28]:
#产生3x4的空的person_dtype的结构体数组
people = np.empty((3,4), person_dtype)

In [30]:
people['name'] = [['Brad', 'Jane', 'John', 'Fred'],
                  ['Henry', 'George', 'Brain', 'Amy'],
                  ['Ron', 'Susan', 'Jennife', 'Jill']]

In [31]:
people['age'] = [[33, 25, 47, 54],
                 [29, 61, 32, 27],
                 [19, 33, 18, 54]]

In [32]:
people['weight'] = [[135., 105., 255., 140.],
                    [154., 202., 137., 187.],
                    [188., 135., 88., 145.]]

In [33]:
print (people)

[[(b'Brad', 33,  135.) (b'Jane', 25,  105.) (b'John', 47,  255.)
  (b'Fred', 54,  140.)]
 [(b'Henry', 29,  154.) (b'George', 61,  202.) (b'Brain', 32,  137.)
  (b'Amy', 27,  187.)]
 [(b'Ron', 19,  188.) (b'Susan', 33,  135.) (b'Jennife', 18,   88.)
  (b'Jill', 54,  145.)]]


In [35]:
people[-1][-1]

(b'Jill', 54,  145.)

In [36]:
#从文本中可以读取结构化数组

In [37]:
%%writefile people.txt
name age weight
amy 11 38.2
john 10 40.3
bill 12 21.2

Writing people.txt


In [38]:
person_dtype = np.dtype([('name', 'S10'), ('age', 'int'), ('weight', 'float')])

people = np.loadtxt('people.txt', 
                    skiprows=1,
                    dtype=person_dtype)

In [39]:
people

array([(b'amy', 11,  38.2), (b'john', 10,  40.3), (b'bill', 12,  21.2)],
      dtype=[('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [42]:
people['name']
#查看某个域的值

array([b'amy', b'john', b'bill'],
      dtype='|S10')

In [ ]:
import os
os.remove('people.txt')

In [44]:
%%writefile wood.csv
item,material,number
100,oak,33
110,maple,14
120,oak,7
145,birch,3

Writing wood.csv


In [48]:
tree_to_int = dict(oak = 1,
                   maple=2,
                   birch=3)
def convert(s):
    return tree_to_int.get(s,0)

In [49]:
#使用 genfromtxt 载入数据，可以自动从第一行读入属性名称：

In [50]:
data = np.genfromtxt('wood.csv',
                     delimiter=',', # 逗号分隔
                     dtype=np.int, # 数据类型
                     names=True,   # 从第一行读入域名
                     converters={1:convert}#第一列使用convert方法
                    )

In [51]:
data

array([(100, 0, 33), (110, 0, 14), (120, 0,  7), (145, 0,  3)],
      dtype=[('item', '<i4'), ('material', '<i4'), ('number', '<i4')])

In [52]:
data['item']

array([100, 110, 120, 145])

In [53]:
os.remove('wood.csv')

In [58]:
particle_dtype = np.dtype([('position',[('x','float'),('y','float')]),
                           ('mass','float')
                           ]
                            ) 
                

In [59]:
%%writefile data.txt
2.0 3.0 42.0
2.1 4.3 32.5
1.2 4.6 32.3
4.5 -6.4 23.3

Overwriting data.txt


In [60]:
data = np.loadtxt('data.txt', dtype=particle_dtype)

In [61]:
data

array([(( 2. ,  3. ),  42. ), (( 2.1,  4.3),  32.5), (( 1.2,  4.6),  32.3),
       (( 4.5, -6.4),  23.3)],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('mass', '<f8')])

In [63]:
data['position']['x']
#可以进行索引

array([ 2. ,  2.1,  1.2,  4.5])

In [64]:
os.remove('data.txt')