In [1]:
import numpy as np
import pandas as pd

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a*b #两个矩阵的对应点元素的乘积

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [6]:
a**3 #次方运算

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [7]:
1/a #标量对每个元素除

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [12]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [9]:
A.dot(B)#矩阵的.dot是作为矩阵乘

array([[22, 28],
       [49, 64]])

随机数生成

In [19]:
np.random.randn(3,4)#生成标准高斯分布

array([[ 0.18109011, -0.25665243, -1.67165045,  1.76596162],
       [ 2.66516795,  0.75271261, -0.6319433 ,  0.59830253],
       [-1.11524264,  0.21890611,  0.1759291 ,  0.89283958]])

In [21]:
np.random.random([3,4]) #生成标准的均匀分布

array([[ 0.75677726,  0.18582287,  0.88352545,  0.09632766],
       [ 0.00160343,  0.88923573,  0.00621647,  0.83389396],
       [ 0.33003858,  0.99787918,  0.16163586,  0.71901207]])

In [30]:
rint = np.random.randint(1,4,size = [5,5]) #生成1,4的随机数矩阵

array([[3, 2, 1, 2, 2],
       [2, 3, 3, 2, 1],
       [2, 1, 1, 2, 2],
       [3, 3, 2, 3, 3],
       [1, 3, 2, 3, 1]])

In [31]:
A.sum() #矩阵所有元素的和

21

In [36]:
C = np.array([[1,4,2],[2,3,1]])
C

array([[1, 4, 2],
       [2, 3, 1]])

In [45]:
C.min(axis = (1)) #axis= 0是列方向

array([1, 1])

In [51]:
D = np.arange(24)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
D.reshape([6,4],order = 'F')#reshape是将一个向量变换成需要形状的矩阵
#order = 'F'为按列的方向reshape

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [57]:
D#可以看到reshape只是返回一个矩阵对原来的矩阵并没有改变

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
E = D.reshape([6,4],order = 'F')
E

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [63]:
#按照某个方向进行累加求和
E.cumsum(axis = 1)

array([[ 0,  6, 18, 36],
       [ 1,  8, 21, 40],
       [ 2, 10, 24, 44],
       [ 3, 12, 27, 48],
       [ 4, 14, 30, 52],
       [ 5, 16, 33, 56]], dtype=int32)