In [4]:
import numpy as np

In [5]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [6]:
a[2] #可以看到和matlab不同，python中是从0开始的标号.
#翻译代码的时候需要特别注意

4

In [7]:
a[2:4] #可使用:运算符来索引，这个与matlab中是同样的

array([4, 9], dtype=int32)

In [8]:
a_slice = a[2:4]
a_slice[0]=5
a
#特别注意！！！ 使用slice并不是复制出的副本，而是对于原数组a的地址的储存
#当对a_slice操作的时候原数组a也受到了明细的影响！

array([ 0,  1,  5,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
#如果使用slice复制出一个相互独立的数组的话也可以
a_slicecopy = a[2:4].copy()
print(a_slicecopy)
a_slicecopy[0] = 4
print(a_slicecopy)
print(a)

[5 9]
[4 9]
[ 0  1  5  9 16 25 36 49 64 81]


多维数组

In [10]:
def f(y,x):
    return 4 * x + y
b = np.fromfunction(f,(3,2),dtype = int) 
#这个函数相当于把每个值的所在的维数作为
#函数的输入,注意也是从0开始计数的！
#而且严格按照函数定义的变量的顺序进行
print(b)

[[0 4]
 [1 5]
 [2 6]]


In [11]:
b[0]

array([0, 4])

In [12]:
print(b[0][1]) #选中元素的方法
print(b[0,1])
print(b[:,1])

4
4
[4 5 6]


In [13]:
c = np.zeros([4,5])
print(c)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [14]:
column_length = c.shape[1]
column_length

5

In [15]:
for i in range(c.shape[0]):
    c[i]=i 
    print(c[i])
c

[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.]
[ 3.  3.  3.  3.  3.]


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.]])

Boolean Indexing

In [16]:
week_days = np.array(['Monday','Tuesday','Wednesday','Thursday','Friday'])

In [23]:
work_time = np.round(np.random.randn(5,5) + 8.0 , 2)
print(work_time.T)
work_time

[[ 7.68  9.76  7.56  8.61  6.83]
 [ 7.21  9.64  8.42  8.54  8.34]
 [ 9.    8.72  8.11  8.38  6.08]
 [ 7.78  8.03  6.54  7.4   8.06]
 [ 7.2   8.46  8.92  8.54  5.74]]


array([[ 7.68,  7.21,  9.  ,  7.78,  7.2 ],
       [ 9.76,  9.64,  8.72,  8.03,  8.46],
       [ 7.56,  8.42,  8.11,  6.54,  8.92],
       [ 8.61,  8.54,  8.38,  7.4 ,  8.54],
       [ 6.83,  8.34,  6.08,  8.06,  5.74]])

In [20]:
week_days == 'Monday'

array([ True, False, False, False, False], dtype=bool)

In [24]:
work_time.T[week_days == 'Monday'] 

array([[ 7.68,  9.76,  7.56,  8.61,  6.83]])