In [1]:
import numpy as np

In [2]:
#对于数组有时要进行类似switch 和case条件选择
#choose 函数完成这一功能


In [3]:
control = np.array([[1,0,1],
                    [2,1,0],
                    [1,2,2]])

np.choose(control, [10, 11, 12])

array([[11, 10, 11],
       [12, 11, 10],
       [11, 12, 12]])

In [4]:
i0 = np.array([[0,1,2],
               [3,4,5],
               [6,7,8]])
i2 = np.array([[20,21,22],
               [23,24,25],
               [26,27,28]])
control = np.array([[1,0,1],
                    [2,1,0],
                    [1,2,2]])

np.choose(control, [i0, 10, i2])

array([[10,  1, 10],
       [23, 10,  5],
       [10, 27, 28]])

In [11]:
a = np.array([[ 0, 1, 2], 
              [10,11,12], 
              [20,21,22]])

In [6]:
np.choose(a < 10, (a, 10))

array([[10, 10, 10],
       [10, 11, 12],
       [20, 21, 22]])

In [7]:
#要达到同上的效果最好的方法是,
#缺点是下面这个方法就把原来的数组给改变了

In [12]:
a[a<10] = 10

In [15]:
a

array([[10, 10, 10],
       [10, 11, 12],
       [20, 21, 22]])

In [16]:
a = np.array([[ 0, 1, 2], 
              [10,11,12], 
              [20,21,22]])

lt = a < 10
gt = a > 15

choice = lt + 2 * gt
choice

array([[1, 1, 1],
       [0, 0, 0],
       [2, 2, 2]])

In [17]:
np.choose(choice, (a, 10, 15))

array([[10, 10, 10],
       [10, 11, 12],
       [15, 15, 15]])

In [18]:
a

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])