In [1]:
import numpy as np

In [2]:
a = np.mat('1,2,3;4,5,6')

In [4]:
np.negative(a)

matrix([[-1, -2, -3],
        [-4, -5, -6]])

In [21]:
#hypot返回对应点到远点的距离
np.hypot(3*np.ones((3, 3)), 4*np.ones((3, 3)))


array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [13]:
#类型处理
iscomplexobj
iscomplex
isrealobj
isreal
imag
real
real_if_close
isscalar
isneginf
isposinf
isinf
isfinite
isnan
nan_to_num
common_type
typename`

In [22]:
np.inf

inf

In [23]:
-np.inf

-inf

In [24]:
np.nan#非法值

nan

In [25]:
#检查是否是无穷
np.isinf(1.)

False

In [26]:
np.isinf(-np.inf)

True

In [29]:
np.array([1])/0

H:\ToolPrograms\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf])

In [31]:
#只有0/0会的到nan,非0值/0会得到无穷
a = np.arange(5.0) -1
b = a / 0.0
b

H:\ToolPrograms\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
H:\ToolPrograms\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-inf,  nan,  inf,  inf,  inf])