In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
#查看数组属性
type(a)

numpy.ndarray

In [5]:
#查看数组的数据类型
a.dtype

dtype('int32')

In [6]:
#查看每个元素所占字节
a.itemsize

4

In [9]:
#查看形状，会返回一个元组，每个元素代表这一维的元素数目：
print(a.shape)
print(np.shape(a))

(4,)
(4,)


In [12]:
#查看元素数目,使用size()函数
np.size(a)

4

In [14]:
#查看所有元素所占的空间
a.nbytes

16

In [15]:
#查看数组的维数
a.ndim

1

In [19]:
#fill方法将数组设为设定值
#数组中要求所有元素的数据类型相同，传入参数的类型与数组类型不一样
#，传入参数的数据类型将会被转换为数组的数据类型
a.fill(-5)
a

array([-5, -5, -5, -5])

In [21]:
#数组也支持索引和切片的操作
a =np.array([0, 1, 2, 3])
a[0]

0

In [23]:
#可以直接修改位置上的数值
a[0] = 10
a

array([10,  1,  2,  3])

In [25]:
#切片，支持负索引：
a[-2:0:-1]

array([2, 1])

In [26]:
#假设我们记录一辆汽车表盘上每天显示的里程数：
od = np.array([21000, 21180, 21240, 22100, 22400])
dist = od[1:] - od[:-1]
dist

array([180,  60, 860, 300])

In [39]:
#array 定义多维数组
a = np.array([[ 0, 1, 2, 3],
           [10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [40]:
a.shape

(2, 4)

In [41]:
#二维数组索引
#也可以利用索引赋值
a[1,2]

12

In [44]:
#需要注意！！，切片在python内存中使用的是引用规则
#如果使用引用对b进行修改a中也会有相应的改动
print(a)
b = a[1,2:3]
print(b)
b[0] = 0
print(a)
print(b)

[[ 0  1  2  3]
 [10 11 12 13]]
[12]
[[ 0  1  2  3]
 [10 11  0 13]]
[0]


In [37]:
a = np.array([0,1,2,3,4])
b = a[2:4]
print (b)
b[0] = 10
a

[2 3]


array([ 0,  1, 10,  3,  4])

In [46]:
#如果需要避开引用机制,b指向新的数值那么我们就使用copy()方法
a = np.array([0,1,2,3,4])
b = a[2:4].copy()
b[0] = 10
a

array([0, 1, 2, 3, 4])

In [47]:
#花式索引
#与切片不同，花式索引返回的是原对象的一个复制而不是引用。

In [48]:
a = np.arange(0, 80, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [49]:
#使用数组直接对任意位置索引
indices = [1, 2, -3]
y = a[indices]
print(y)

[10 20 50]


In [52]:
#布尔数组索引
mask = np.array([0,1,1,-1,0,1,0,0],
            dtype=bool)
mask

array([False,  True,  True,  True, False,  True, False, False], dtype=bool)

In [53]:
a[mask]

array([10, 20, 30, 50])

In [55]:
#使用bool表达式生成mask直接可以选出所有大于0.5的值
a = np.random.rand(10)
print(a)
mask = a>0.5
print(mask)
a[mask]

[ 0.77790678  0.92943854  0.68622185  0.78858731  0.43373224  0.78044031
  0.35186286  0.19784235  0.6547175   0.8254519 ]
[ True  True  True  True False  True False False  True  True]


array([ 0.77790678,  0.92943854,  0.68622185,  0.78858731,  0.78044031,
        0.6547175 ,  0.8254519 ])

In [56]:
y

array([10, 20, 50])

In [58]:
#where()函数会以元组的形式返回所有满足条件的索引
a = np.array([0, 12, 5, 20])
np.where(a>10)

(array([1, 3], dtype=int64),)

In [63]:
#如果需要的返回值直接是一个数组，我们可以把返回元组的第一个值索引出来
indices = np.where(a > 10)[0]
#indices = indices[0]
indices


array([1, 3], dtype=int64)

In [66]:
#挑选出满足条件的数值的最简单的方法：
a[(a>10)]

array([12, 20])