In [1]:
import numpy as np

In [8]:
a = np.array([[1,2,3],[4,5,6]])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b = np.array([[1,2],[3,4],[5,6]])

In [11]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
np.dot(a,b)
#array的dot是矩阵乘的方式

array([[22, 28],
       [49, 64]])

In [16]:
np.spacing(1)
#分度

2.2204460492503131e-16