In [3]:
import numpy as np

In [6]:
#在构建数组的时候我们可以指定数组的数据类型
a = np.array([1,2,3,4],dtype = 'float32')
a

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [9]:
a = np.array([1,2,3,4],dtype = 'uint8')
a

array([1, 2, 3, 4], dtype=uint8)

In [12]:
#可以从二进制数据中读取数据
a = np.array([102,111,212], 
          dtype='uint8')
a.tofile('foo.dat')

In [17]:
b = np.fromfile('foo.dat',dtype = 'uint8')
b

array([102, 111, 212], dtype=uint8)

In [18]:
import os
os.remove('foo.dat')

In [19]:
#查询ASCII码，可以使用ord()函数

In [20]:
ord('k')

107

In [22]:
#任意类型数组
a = np.array([1,1.2,'hello', [10,20,30]], 
          dtype=object)

In [23]:
a*2

array([2, 2.4, 'hellohello', list([10, 20, 30, 10, 20, 30])], dtype=object)

In [25]:
#可以对数组的类型进行转换
#asarray()函数返回的是数组的一份复制，原来的数组不会直接被改变
a = np.array([1.5, -3], 
         dtype='float32')
a

array([ 1.5, -3. ], dtype=float32)

In [36]:
np.asarray(a,dtype = 'float64')

array([ 1.5, -3. ])

In [38]:
b=np.asarray(a, dtype='uint8')
b

array([  1, 253], dtype=uint8)

In [41]:
#view 方法
#view 会将 a 在内存中的表示看成是 uint8 进行解析：
a = np.array((1,2,3,4), dtype='int32')
print(a)
b = a.view('uint8')
print(b)

[1 2 3 4]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0]


In [42]:
#修改 a 会修改 b 的值，因为共用一块内存：
a[0] = 2**30
b

array([ 0,  0,  0, 64,  2,  0,  0,  0,  3,  0,  0,  0,  4,  0,  0,  0], dtype=uint8)